apiVersion: v1
kind: Service
metadata:
    name: mysql
spec:
    selector:
        app: mysql
    ports:
        -
            protocol: TCP
            port: 3306
            targetPort: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
spec:
    replicas: 1
    strategy:
        type: Recreate
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
                -
                    name: mysql
                    image: mariadb:latest
                    ports:
                        - containerPort: 3306
                    volumeMounts:
                        -
                            name: mysql-storage
                            mountPath: /var/lib/mysql
                            subPath: mysql
                    env:
                        -
                            name: MARIADB_DATABASE
                            value: ibproekt
                        
                        -
                            name: MARIADB_ROOT_PASSWORD_HASH
                            value: "*E4AC4150AA7941E1CEA8380831B29A6512A55948"

            volumes:
                -
                    name: mysql-storage
                    persistentVolumeClaim:
                        claimName: mysql-storage