apiVersion: v1
kind: Service
metadata:
    name: php

spec:
    type: ClusterIP
    selector:
        app: php
    ports:
        - protocol: TCP
          port: 9000
          targetPort: 9000


---


apiVersion: apps/v1
kind: Deployment
metadata:
    name: php

spec:
    replicas: 2
    selector:
        matchLabels:
            app: php
    
    template:
        metadata:
            labels:
                app: php

        spec:
            containers:
                -
                    name: php
                    image: drajver5siti/totp-php:1.1
                    ports:
                        -
                            containerPort: 9000
                    env:
                        -
                            name: MARIADB_HOST
                            value: mysql

                        -
                            name: MARIADB_DATABASE
                            value: ibproekt

                        -
                            name: MARIADB_USER
                            value: root

                        -
                            name: MARIADB_ROOT_PASSWORD_HASH
                            value: "*E4AC4150AA7941E1CEA8380831B29A6512A55948"